package org.cotrix.lifecycle;

import java.io.Serializable;

/**
 * A factory of {@link Lifecycle}s.
 * 
 * @author Fabio Simeoni
 *
 */
public interface LifecycleFactory extends Serializable {

	/**
	 * The name of the default lifecycle.
	 */
	public static final String DEFAULT = "__default__";
	
	/**
	 * Returns the name of lifecycle generated by this factory.
	 * @return
	 */
	String name();
	
	/**
	 * Creates a lifecycle for a given resource.
	 * @param id the resource identifier
	 * @return the lifecycle 
	 */
	Lifecycle create(String id);
	
}
