package org.cotrix.core;

/**
 * CotrixException is a RuntimeException
 * 
 * To avoid loads of try catches in the code, CotrixException is a runtime
 * exception. This assumes however that all code is very well unit tested!
 * 
 * 
 * @author Erik van Ingen
 */

public class CotrixException extends RuntimeException {

	/**
	 * Generated by Eclipse.
	 */
	private static final long serialVersionUID = 590457791260365759L;

	public CotrixException(Throwable e) {
		super(e);
	}

	public CotrixException(String newMessage) {
		super(newMessage);
	}

	public CotrixException(String msg, Throwable e) {
		super(msg, e);
	}

}
